version: "{branch} {build}"
image: Visual Studio 2017

deploy:
  # FTP deployment provider settings
  - provider: FTP
    protocol: ftp
    host: localhost
    username: scott
    password: tigger
    active_mode: false
    beta: true      # enable alternative FTP library for 'ftp' and 'ftps' modes
    debug: true     #

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  FTP_TEST_PORT: 21

build_script:
  # see http://help.appveyor.com/discussions/problems/5975-the-process-cannot-access-the-file-because-it-is-being-used-by-another-process
  - gradlew.bat --info --no-daemon check

cache:
  - C:\Users\appveyor\.gradle

matrix:
  fast_finish: true